// components/shared/GetStarted.vue
<template>
  <section>
    <h2 class="title-global">
      Ready to <span class="mark">get started?</span>
    </h2>
    <div class="contact-us">
      <h4>
        Contact us at <a href="mailto:hello@scrumlaunch.com">hello@scrumlaunch.com</a> or fill out the form
      </h4>
      <div class="info-wrap">
        <div class="hero">
          <nuxt-img src="/shared/get-started/hero.svg" alt="get-started-hero-img" />
        </div>
        <form>
          <h3>
            Company Details
          </h3>
          <div class="main-inputs">
            <div class="single-inputs">
              <div class="input">
                <label for="name">
                  Name*
                </label>
                <input
                  v-model="name"
                  placeholder="Enter your name"
                  type="text"
                  id="name"
                />
              </div>
              <div class="input">
                <label for="email">
                  Email*
                </label>
                <input
                  v-model="email"
                  placeholder="Enter your email"
                  type="email"
                  id="email"
                />
              </div>
              <div class="input">
                <label for="company">
                  Company*
                </label>
                <input
                  v-model="company"
                  placeholder="Enter company name"
                  type="text"
                  id="company"
                />
              </div>
            </div>
            <div class="text-areas">
              <div class="input">
                <label for="details">
                  Any details you’d like to share?
                </label>
                <textarea 
                  v-model="details"
                  type="text"
                  id="details"
                  placeholder="Enter your message"
                />
              </div>
            </div>
          </div>
          <div class="additional-inputs">
            <h3>
              Additional Information
            </h3>
            <div class="selects">
              <div class="input">
                <label for="company">
                  Company Size
                </label>
                <select
                  v-model="size"
                  type="text"
                  id="company"
                >
                <option disabled value="">Select company size</option>
                <option v-for="option in companySizeOptions" :value="option.value">
                  {{ option.text }}
                </option>
                </select>
              </div>
              <div class="input">
                <label for="company">
                  Total Project Budget
                </label>
                <select
                  v-model="budget"

                  type="text"
                  id="company"
                  placeholder="Select project budget"
                >
                  <option disabled value="">Select project budget</option>
                  <option v-for="option in projectBudgetOptions" :value="option.value">
                    {{ option.text }}
                  </option>

                </select>
              </div>
            </div>
          </div>
        </form>
      </div>
      <BaseButton @click="sendForm()">
        Send message
      </BaseButton>
    </div>
  </section>
</template>

<script>
import axios from 'axios';

export default {
  data() {
    return {
      is_blocked: false,
      is_sent: false,
      is_done: false,

      name: '',
      email: '',
      company: '',
      details: '',
      size: '',
      budget: '',

      companySizeOptions: [
        { text: '1-50', value: '1-50' },
        { text: '50-200', value: '50-200' },
        { text: '200-1000', value: '200-1000' },
        { text: '1000-5000+', value: '1000-5000+' },
        { text: '10,000+', value: '10,000+' },
      ],
      projectBudgetOptions: [
        { text: 'Less than $10,000', value: 'Less than $10,000' },
        { text: '$10,000 to $49,999', value: '$10,000 to $49,999' },
        { text: '$50,000 to $199,999', value: '$50,000 to $199,999' },
        { text: '$200,000 to $999,999', value: '$200,000 to $999,999' },
        { text: '$1,000,000 to $9,999,999', value: '$1,000,000 to $9,999,999' },
        { text: '$10,000,000 +', value: '$10,000,000 +' },
      ]
    };
  },
  methods: {
    async submitForm() {
      try {
        const response = await axios.post('/api/contact-us', this.name);
        console.log(response);
      } catch (error) {
        console.error(error);
      }
    },

    sendForm() {
      this.is_sent = true
      this.is_blocked = true

      const data = {
        name: this.name,
        email: this.email,
        company: this.company,
        details: this.details,
        size: this.size,
        budget: this.budget,
      }

      this.$axios.$post('/api/company-contact', data).then(() => {
        this.name = ''
        this.email = ''
        this.company = ''
        this.details = ''
        this.size = ''
        this.budget = ''

        this.is_blocked = false
        this.is_done = true

        this.track()

        setTimeout(() => {
          this.is_sent = false
          this.is_done = false
        }, 5000)
      })
    },

    track() {
      if (this.$gtag !== undefined) {
        this.$gtag.event('conversion', {
          send_to: 'AW-10868833249/37WpCK7nhbQDEOH31L4o',
        })
      }
    },
  },
};
</script>

<style lang="scss" scoped>

section {
  padding-left: 0;
  h2 {
    margin-bottom: 40px;
    
    @include tablet-and-up {
      margin-bottom: 60px;
    }

    @include desktop-and-up {
      margin-bottom: 80px;
      text-align: center;
    }
  }

  .contact-us {
    background-color: $main-black;
    padding: 40px 20px;

    @include tablet-and-up {
      padding: 60px 32px;
    }

    h4 {
      font-weight: 700;
      font-size: 18px;
      color: #fff;
      margin-bottom: 32px;

      @include tablet-and-up {
        font-size: 24px;
      }

      @include desktop-and-up {
        font-size: 30px;
      }

      a {
        text-decoration: none;
        color: $main-green;
      }
    }

    .info-wrap {
      display: flex;
      margin-bottom: 32px;
      @include tablet-and-up {
        margin-bottom: 60px;
      }

      .hero {
        display: none;

        @include desktop-and-up {
          display: block;
        }
      }
      form {
        width: 100%;
        background-color: $main-green;
        padding: 24px 12px;
        text-align: left;

        @include tablet-and-up {
          padding: 32px;
        }

        .input {
          display: flex;
          flex-direction: column;
          margin-bottom: 16px;

          @include desktop-and-up {
            margin-bottom: 32px;
          }

          label {
            font-weight: 700;
            font-size: 16px;
            text-transform: uppercase;
          }

          input,textarea,select {
            border: 1px solid $main-black;
            padding: 8px 14px;
            font-size: 14px;

            &::placeholder {
              color: $main-black;
            }

            @include tablet-and-up {
              font-size: 16px;
            }
          }
        }

        h3 {
          font-weight: 700;
          font-size: 20px;
          margin-bottom: 12px;
          
          @include tablet-and-up {
            font-size: 24px;
          }

          @include desktop-and-up {
            font-size: 30px;
          }

        }

        .main-inputs {
          display: flex;
          flex-direction: column;
          border-bottom: 1px solid $main-black;

          @include tablet-and-up {
            flex-direction: row;
            gap: 24px;
          }

          .single-inputs {
            @include tablet-and-up {
              flex-basis: 0;
              flex-grow: 1;
            }
          }

          .text-areas {
            @include tablet-and-up {
              flex-basis: 0;
              flex-grow: 1;
              margin-bottom: 16px;
            }

            @include desktop-and-up {
              margin-bottom: 32px;
            }

            .input {
              height: 100%;

              textarea {
                height: 100%;
              }
            }
          }
        }

        .additional-inputs {
          margin-top: 20px;

          @include desktop-and-up {
            margin-top: 32px;
          }

          .selects {
            display: flex;
            flex-direction: column;
            @include tablet-and-up {
              flex-direction: row;
              gap: 20px;
            }

            .input {
              @include tablet-and-up {
                flex-grow: 1;
                flex-basis: 0;
              }
              
              @include desktop-and-up {
                margin-bottom: 0;
              }
            }
          }
        }
      }
    }
    button {
      margin: auto;
    }
  }
}

</style>

// components/get-started/get-started.tsx
'use client';

import { useState } from 'react';
import { useForm } from 'react-hook-form';
import Container from '@/components/ui/container';
import Title from '@/components/ui/title';
import BaseButton from '@/components/ui/base-button';
import CustomSelect from '@/components/ui/custom-select';
import styles from './styles.module.scss';
import cn from 'classnames';
import Image from 'next/image';
interface FormData {
  name: string;
  email: string;
  company: string;
  details: string;
  size: string;
  budget: string;
}

export default function GetStarted() {
  const [isSent, setIsSent] = useState(false);
  const [isDone, setIsDone] = useState(false);
  const [isBlocked, setIsBlocked] = useState(false);

  const {
    register,
    handleSubmit,
    formState: { errors },
    setValue,
    watch
  } = useForm<FormData>();

  const companySizeOptions = ['1-50', '50-200', '200-1000', '1000-5000+', '10,000+'];
  const projectBudgetOptions = [
    'Less than $10,000',
    '$10,000 to $49,999',
    '$50,000 to $199,999',
    '$200,000 to $999,999',
    '$1,000,000 to $9,999,999',
    '$10,000,000 +'
  ];

  const validateEmail = (email: string) => {
    const emailRegEx = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}$/i;
    return emailRegEx.test(email) || 'Please enter a valid email';
  };

  const onSubmit = async (data: FormData) => {
    console.log(data);

    // try {
    //   setIsSent(true);
    //   setIsBlocked(true);

    //   await fetch('/api/company-contact', {
    //     method: 'POST',
    //     headers: {
    //       'Content-Type': 'application/json',
    //     },
    //     body: JSON.stringify(data),
    //   });

    //   setIsDone(true);
    //   setIsBlocked(false);

    //   if (typeof window !== 'undefined' && (window as any).gtag) {
    //     (window as any).gtag('event', 'conversion', {
    //       send_to: 'AW-10868833249/37WpCK7nhbQDEOH31L4o',
    //     });
    //   }

    //   setTimeout(() => {
    //     setIsSent(false);
    //     setIsDone(false);
    //   }, 5000);
    // } catch (error) {
    //   console.error('Error sending form:', error);
    //   setIsBlocked(false);
    // }
  };

  return (
    <>
      <div className={styles['get-started-title']}>
        <Container>
          <Title variant="h2" className={styles['get-started-title__title']}>
            Ready to <span className={styles['get-started-title__mark']}>get started?</span>
          </Title>
        </Container>
      </div>

      <section className={styles['get-started']}>
        <Container>
          <div className={styles['get-started__contact']}>
            <p className={styles['get-started__subtitle']}>
              Contact us at <a href="mailto:hello@scrumlaunch.com">hello@scrumlaunch.com</a> or fill out the form
            </p>

            <div className={styles['get-started__content']}>
              <div className={styles['get-started__hero']}>
                <Image
                  src="/images/home/get-started/hero.svg"
                  className={styles['get-started__hero-image']}
                  alt="get-started-hero"
                  width={100}
                  height={100}
                />
              </div>

              <form className={styles['get-started__form']} onSubmit={handleSubmit(onSubmit)}>
                <Title variant="h3" className={styles['get-started__form-title']}>Company Details</Title>

                <div className={styles['get-started__main-inputs']}>
                  <div className={styles['get-started__single-inputs']}>
                    <div className={styles['get-started__input-wrapper']}>
                      <label htmlFor="name">Name*</label>

                      <div className={cn(styles['get-started__input'], {
                        [styles['get-started__input--error']]: errors.name
                      })}>
                        <input
                          id="name"
                          placeholder="Enter your name"
                          {...register('name', { required: 'Please enter your name' })}
                        />
                        {errors.name && (
                          <div className={styles['get-started__error']}>
                            <div className={styles['get-started__error-popup']}>
                              {errors.name.message}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>

                    <div className={styles['get-started__input-wrapper']}>
                      <label htmlFor="email">Email*</label>

                      <div className={cn(styles['get-started__input'], {
                        [styles['get-started__input--error']]: errors.email
                      })}>
                        <input
                          id="email"
                          placeholder="Enter your email"
                          {...register('email', {
                            required: 'Please enter your email',
                            validate: validateEmail
                          })}
                        />
                        {errors.email && (
                          <div className={styles['get-started__error']}>
                            <div className={styles['get-started__error-popup']}>
                              {errors.email.message}
                            </div>
                          </div>
                        )}
                      </div>
                    </div>

                    <div className={styles['get-started__input-wrapper']}>
                      <label htmlFor="company">Company</label>

                      <div className={styles['get-started__input']}>
                        <input
                          id="company"
                          placeholder="Enter company name"
                          {...register('company')}
                        />
                      </div>
                    </div>
                  </div>

                  <div className={styles['get-started__text-areas']}>
                    <div className={styles['get-started__input-wrapper']}>
                      <label htmlFor="details">Any details you&apos;d like to share?</label>

                      <textarea
                        id="details"
                        placeholder="Enter your message"
                        {...register('details')}
                      />
                    </div>
                  </div>
                </div>

                <div className={styles['get-started__additional']}>
                  <Title variant="h3" className={styles['get-started__form-title']}>
                    Additional Information
                  </Title>

                  <div className={styles['get-started__selects']}>
                    <CustomSelect
                      label="Company Size"
                      options={companySizeOptions}
                      placeholder="Select company size"
                      value={watch('size')}
                      onChange={(value) => setValue('size', value)}
                    />

                    <CustomSelect
                      label="Total Project Budget"
                      options={projectBudgetOptions}
                      placeholder="Select project budget"
                      value={watch('budget')}
                      onChange={(value) => setValue('budget', value)}
                    />
                  </div>
                </div>
              </form>

              {isSent && (
                <div className={cn(styles['get-started__message'], {
                  [styles['get-started__message--blocked']]: isBlocked
                })}>
                  {isDone && (
                    <>
                      <div className={styles['get-started__message-animation']}>
                      </div>

                      <p className={styles['get-started__message-title']}>
                        Your message<br />has been sent
                      </p>
                    </>
                  )}
                </div>
              )}
            </div>

            <BaseButton
              onClick={handleSubmit(onSubmit)}
              className={styles['get-started__submit']}
            >
              Send message
            </BaseButton>
          </div>
        </Container>
      </section>
    </>
  );
}
