// components/hire-developers/ClientTestimonials.vue
<template>
  <div class="container">
    <div class="leading_result">
      <h3 class="title">Client Testimonials</h3>
      <div class="arrow_container">
        <div class="testimonials_nav_prev" @click="prevStep()"></div>
        <div class="testimonials_nav_next" @click="nextStep()"></div>
      </div>
      <div class="slider_container">
        <div>
          <img
            :src="sliderInfo[sliderStep].image"
            :alt="sliderInfo[sliderStep].name"
            class="image"
          />
        </div>
        <div class="container_with_icon">
          <div class="ct">
            <p class="name">{{ sliderInfo[sliderStep].name }}</p>
            <div class="company_information__container">
              <p>{{ sliderInfo[sliderStep].position }}</p>
              <p class="company_information__dot">
                {{ sliderInfo[sliderStep].company }}
              </p>
            </div>
          </div>
        </div>
        <div class="badge">
          <img src="/images/hire-developers/testimonials/results_clutch.svg" />
        </div>
        <p class="feedback">{{ sliderInfo[sliderStep].feedback }}</p>
        <div class="btn_wrap">
          <BaseButton @click="validateForm()">
            <div class="btn-inner">
              <img src="/images/hire-developers/testimonials/clutch.svg" alt="clutch">
              <p>See Rob's full review</p>
            </div>
          </BaseButton>
        </div>
      </div>
    </div>
  </div>
</template>

<script>
import BaseButton from '@/components/BaseButton.vue'

export default {
  components: {
    BaseButton
  },

  data: () => ({
    sliderInfo: {
      1: {
        image: '/images/industry-leading-results/rob_carrol.png',
        withIcon: true,
        feedback:
          '“ScrumLaunch software developers have enabled CampusReel to go from an idea to a product with millions of monthly unique users over the past 5 years. We could not have gotten to where we are today without them.”',
        name: 'Rob Carroll',
        position: 'CEO',
        company: 'CampusReel',
      },
      2: {
        image: '/images/industry-leading-results/matt_glick.jpeg',
        withIcon: false,
        feedback:
          "“ScrumLaunch has been with us since day 1. We've been working with them for 5 years. From an idea to a market leader in our space backed by leading venture funds”",
        name: 'Matt Glick',
        position: 'CEO',
        company: 'Gipper',
      },
      3: {
        image: '/images/industry-leading-results/clare_maxwell.jpeg',
        withIcon: false,
        feedback:
          '“ScrumLaunch enabled us to completely restructure Community Funded over the past two years and reduce costs by 5x making the company profitable and the technology much more scalable and solid.”',
        name: 'Clare Maxwell',
        position: 'Venture Investor & Board Observer',
        company: 'Community Funded',
      },
      4: {
        image: '/images/industry-leading-results/nami_baral.jpeg',
        withIcon: false,
        feedback:
          '“ScrumLaunch was an integral partner for the entire lifecycle of our project from launch, venture fundraising to acquisition by a FinTech Unicorn.”',
        name: 'Nami Baral',
        position: 'CEO',
        company: 'Harvest',
      },
    },
    sliderStep: 1,
  }),

  methods: {
    nextStep() {
      if (this.sliderStep === 4) {
        this.sliderStep = 1
      } else {
        this.sliderStep++
      }
    },

    prevStep() {
      if (this.sliderStep === 1) {
        this.sliderStep = 4
      } else {
        this.sliderStep--
      }
    },
  },
}
</script>

<style lang="scss" scoped>
.container {
  padding-bottom: 240px;
  padding-top: 240px;
  padding-left: 8.32%;
  padding-right: 8.32%;

  @media screen and (max-width: 1440px) {
    padding-bottom: 140px;
    padding-top: 140px;
  }

  @media screen and (max-width: 768px) {
    padding-bottom: 80px;
    padding-top: 80px;
    margin-bottom: 0px;
  }
}

.container_with_icon {
  display: flex;
  align-items: center;
  justify-content: center;

  .ct {
    display: flex;
    align-items: center;
    justify-content: center;
    flex-direction: column;
  }

  & > img {
    margin-top: 40px;
    margin-left: 23px;
  }
}

.image {
  border-radius: 50%;
  width: 200px;
  height: 200px;

  @media screen and (max-width: 768px) {
    width: 132px;
    height: 132px;
  }
}

.leading_result {
  position: relative;

  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
}

.arrow_container {
  display: flex;
  align-items: center;
  justify-content: space-between;
  width: 100%;
  position: absolute;
  top: 240px;

  @media screen and (max-width: 1440px) {
    top: 204px;
  }

  @media screen and (max-width: 768px) {
    top: 142px;
  }

  @media screen and (max-width: 425px) {
    top: 174px;
  }
}

.testimonials_nav_prev {
  width: 75px;
  height: 37px;
  background-image: url(/images/industry-leading-results/arrow_not_filled.svg);
  cursor: pointer;

  &:hover {
    background-image: url(/images/industry-leading-results/arrow_filled.svg);
    transform: scale(-1, 1);
  }
}

.testimonials_nav_next {
  width: 75px;
  height: 37px;
  background-image: url(/images/industry-leading-results/arrow_not_filled.svg);
  cursor: pointer;
  transform: scale(-1, 1);

  &:hover {
    background-image: url(/images/industry-leading-results/arrow_filled.svg);
    transform: scale(1, -1);
  }
}

.slider_container {
  margin-top: 80px;
  margin-bottom: 142px;

  @media screen and (max-width: 1440px) {
    margin-top: 60px;
    margin-bottom: 60px;
  }
}

.trusted_container {
  display: flex;
  align-items: center;
  justify-content: center;

  @media screen and (max-width: 768px) {
    & > img {
      max-width: 100%;
    }
  }
}

.title {
  font-weight: 900;
  font-size: 56px;
  line-height: 140%;
  text-transform: uppercase;

  @media screen and (max-width: 1440px) {
    font-size: 48px;
  }

  @media screen and (max-width: 768px) {
    font-size: 24px;
    text-align: left;
  }
}

.feedback {
  font-weight: 400;
  font-size: 26px;
  line-height: 150%;
  text-align: center;
  font-style: italic;
  max-width: 712px;

  @media screen and (max-width: 1440px) {
    font-size: 20px;
    max-width: 437px;
  }

  @media screen and (max-width: 768px) {
    font-size: 16px;
  }
}

.name {
  font-weight: 700;
  font-size: 30px;
  line-height: 140%;
  margin-top: 40px;
  margin-bottom: 12px;

  @media screen and (max-width: 1440px) {
    margin-bottom: 8px;
  }

  @media screen and (max-width: 768px) {
    font-size: 18px;
  }
}

.company_information {
  &__container {
    display: flex;
    align-items: center;
    justify-content: center;
    gap: 28px;

    @media screen and (max-width: 768px) {
      gap: 5px;
      flex-direction: column;
    }

    & > p {
      font-weight: 500;
      font-size: 16px;
      line-height: 150%;
    }

    @media screen and (max-width: 1440px) {
      & > p {
        font-size: 14px;
      }
    }

    @media screen and (max-width: 768px) {
      & > p {
        font-size: 12px;
      }
    }
  }

  &__dot {
    position: relative;

    &::before {
      content: '';
      position: absolute;
      width: 8px;
      height: 8px;
      background: #1e1f21;
      border-radius: 50%;
      top: 0;
      bottom: 0;
      margin: auto;
      left: -18px;
    }
  }
}

.badge {
  margin-top: 60px;
  margin-bottom: 26px;

  @media screen and (max-width: 1440px) {
    margin-top: 40px;
    margin-bottom: 24px;
  }

  @media screen and (max-width: 425px) {
     & > img {
      width: 100%;
     }
  }
}

.btn_wrap {
  margin-top: 80px;

  button {
    margin: auto;
    .btn-inner {
      display: flex;
      gap: 16px;
      
      p {
        margin-top: 3px;
      }
    }
  }
  
}

</style>

// components/client-testimonials/client-testimonials.tsx
'use client';

import { useState, useEffect } from 'react';
import Image from 'next/image';
import Title from '@/components/ui/title';
import Container from '@/components/ui/container';
import cn from 'classnames';
import styles from './styles.module.scss';
import CustomLink from '../custom-link';
import ArrowButton from '@/components/ui/arrow-button';
import { ClutchBlackIcon, ClutchIcon } from '@/components/ui/icons';

const slides = [
  {
    image: '/images/shared/testimonials/rob_carrol.png',
    withIcon: true,
    feedback:
      '"ScrumLaunch software developers have enabled CampusReel to go from an idea to a product with millions of monthly unique users over the past 5 years. We could not have gotten to where we are today without them."',
    name: 'Rob Carroll',
    short: "Rob's",
    position: 'CEO',
    company: 'CampusReel',
    clutch: 'https://clutch.co/profile/scrumlaunch#review-792050',
  },
  {
    image: '/images/shared/testimonials/matt_glick.jpeg',
    withIcon: true,
    feedback:
      '"ScrumLaunch has been with us since day 1. We\'ve been working with them for 5 years. From an idea to a market leader in our space backed by leading venture funds"',
    name: 'Matt Glick',
    short: "Matt's",
    position: 'CEO',
    company: 'Gipper',
    clutch: 'https://clutch.co/profile/scrumlaunch#review-754618',
  },
  {
    image: '/images/shared/testimonials/henry_priest.png',
    withIcon: true,
    feedback:
      '"ScrumLaunch listens to what we need in candidates for our roles."',
    name: 'Henry Priest',
    short: "Henry's",
    position: 'CEO',
    company: 'Benson Hill',
    clutch: 'https://clutch.co/profile/scrumlaunch#review-2038753',
  },
  {
    image: '/images/shared/testimonials/ryan_miller.webp',
    withIcon: false,
    feedback:
      '"The partnership with ScrumLaunch has sped up the product launch of the company\'s product."',
    name: 'Ryan Miller',
    short: "Ryan's",
    position: 'CEO',
    company: 'MODULAR11',
    clutch: 'https://clutch.co/profile/scrumlaunch#review-1925392',
  },
];

const ClientTestimonials = () => {
  const [current, setCurrent] = useState(0);
  const [show, setShow] = useState(false);
  const [isAnimating, setIsAnimating] = useState(false);
  const [transitionName, setTransitionName] = useState('');

  useEffect(() => {
    setShow(true);
  }, []);

  const slide = (dir: number) => {
    if (isAnimating) return;

    setIsAnimating(true);

    if (dir === 1) {
      setTransitionName('slide-next');
    } else {
      setTransitionName('slide-prev');
    }

    setTimeout(() => {
      const len = slides.length;
      setCurrent((prevCurrent) => {
        return (prevCurrent + (dir % len) + len) % len;
      });
      setTransitionName('');
      setIsAnimating(false);
    }, 500);
  };

  return (
    <section className={styles['client-testimonials']}>
      <Container>
        <Title variant="h2" className={styles['client-testimonials__title']}>
          Client Testimonials
        </Title>

        <div className={styles['client-testimonials__carousel']}>
          <ArrowButton
            direction="prev"
            onClick={() => slide(-1)}
            disabled={isAnimating}
            className={cn(
              styles['client-testimonials__navigation-btn--prev']
            )}
          />

          <ArrowButton
            direction="next"
            onClick={() => slide(1)}
            disabled={isAnimating}
            className={cn(
              styles['client-testimonials__navigation-btn--next']
            )}
          />

          <div
            className={cn(
              styles['client-testimonials__slider-group'],
              transitionName
                ? styles[`client-testimonials__slider-group--${transitionName}`]
                : ''
            )}
          >
            {show && (
              <div className={styles['client-testimonials__slide']}>
                <Image
                  className={styles['client-testimonials__avatar']}
                  src={slides[current].image}
                  alt={slides[current].name}
                  width={200}
                  height={200}
                />

                <div className={styles['client-testimonials__description']}>
                  <p className={styles['client-testimonials__name']}>
                    <strong>{slides[current].name}</strong>
                  </p>

                  <div className={styles['client-testimonials__information']}>
                    <p>{slides[current].position}</p>

                    <p className={styles['client-testimonials__dot']}>
                      {slides[current].company}
                    </p>
                  </div>
                </div>

                <ClutchIcon />

                <p className={styles['client-testimonials__feedback']}>
                  {slides[current].feedback}
                </p>
              </div>
            )}
          </div>
        </div>

        <CustomLink
          href={slides[current].clutch}
          className={styles['client-testimonials__button']}
        >
          <ClutchBlackIcon />

          See {slides[current].short} full review
        </CustomLink>
      </Container>
    </section>
  );
};

export default ClientTestimonials;
